listener 1883 
allow_anonymous true

# WebSocket listener
listener 8083
protocol websockets

# Logging
log_timestamp true
log_timestamp_format %Y-%m-%d T%H:%M:%S
log_type all
log_dest file /mosquitto/log/mosquitto.log